name: Road Condition Scraper
on:
  schedule:
    # 日本時間10時に実行 (UTC 1:00)
    - cron: '0 1 * * *'
  workflow_dispatch:
    # 手動実行用

jobs:
  scrape_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Switch to release branch
        run: |
          git fetch origin release || git branch release
          git checkout release
          git merge main --no-edit || true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 selenium pillow webdriver-manager python-dotenv

      - name: Run scraper
        run: python road_scraper.py

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update road condition data $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin release

      - name: Send LINE notification
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_IDS: ${{ secrets.LINE_USER_IDS }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}
          GITHUB_BRANCH: release
        run: python line_notifier.py